In [178]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


In [179]:
df = pd.read_csv('menzili_properties.csv')
df.head(2)

title  premium      price property_type  \
0       A vendre Appartement au lac 2  Premium  1250000.0   Appartement   
1  Appartement S3 à vendre à la Marsa  Premium   360000.0   Appartement   

   property_details_chambres  property_details_salle_de_bain  \
0                        3.0                             NaN   
1                        3.0                             NaN   

   property_details_pieces  property_details_surface_habitable  \
0                      4.0                               178.0   
1                      4.0                               110.0   

   property_details_surface_terrain  property_details_annee_construction  ...  \
0                             178.0                                  NaN  ...   
1                             110.0                                  NaN  ...   

  amenity_interphone amenity_terrasses amenity_chauffage_électriques  \
0                  1                 1                             1   
1                  1                 1                             1   

  amenity_ascenseur amenity_système_alarme  amenity_accès_internet  \
0                 1                      1                       1   
1                 1                      1                       1   

   amenity_vue_mer  amenity_meublé  amenity_chauffage_centrale  \
0                1               0                           1   
1                1               1                           1   

   amenity_cuisine_équipé  
0                       1  
1                       1  

[2 rows x 33 columns]

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16063 entries, 0 to 16062
Data columns (total 33 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   title                                16063 non-null  object 
 1   premium                              16063 non-null  object 
 2   price                                14352 non-null  float64
 3   property_type                        16063 non-null  object 
 4   property_details_chambres            12290 non-null  float64
 5   property_details_salle_de_bain       11332 non-null  float64
 6   property_details_pieces              9481 non-null   float64
 7   property_details_surface_habitable   16063 non-null  float64
 8   property_details_surface_terrain     16063 non-null  float64
 9   property_details_annee_construction  4218 non-null   float64
 10  location                             16063 non-null  object 
 11  neighborhood                

In [181]:
column_to_drop=['title', 'premium','location','link','description']
df.drop(columns=column_to_drop,inplace=True)

In [182]:
df.columns.tolist()

['price',
 'property_type',
 'property_details_chambres',
 'property_details_salle_de_bain',
 'property_details_pieces',
 'property_details_surface_habitable',
 'property_details_surface_terrain',
 'property_details_annee_construction',
 'neighborhood',
 'city',
 'amenity_climatisation',
 'amenity_parabole_tv',
 'amenity_piscine',
 'amenity_accès_handicapé',
 'amenity_place_de_parc',
 'amenity_garage',
 'amenity_jardin',
 'amenity_cheminée',
 'amenity_interphone',
 'amenity_terrasses',
 'amenity_chauffage_électriques',
 'amenity_ascenseur',
 'amenity_système_alarme',
 'amenity_accès_internet',
 'amenity_vue_mer',
 'amenity_meublé',
 'amenity_chauffage_centrale',
 'amenity_cuisine_équipé']

In [183]:
# Create a dictionary mapping old column names to new ones
new_names = {
    'property_details_chambres': 'bedrooms',
    'property_details_salle_de_bain': 'bathrooms',
    'property_details_pieces': 'total_rooms',
    'property_details_surface_habitable': 'living_area',
    'property_details_surface_terrain': 'land_area',
    'property_details_annee_construction': 'construction_year',
     'amenity_climatisation': 'climatisation',
     'amenity_parabole_tv': 'parabole_tv',
     'amenity_piscine': 'pool',
     'amenity_accès_handicapé': 'handicapped_access',
     'amenity_place_de_parc': 'parking',
     'amenity_garage': 'garage',
     'amenity_jardin': 'garden',
        'amenity_cheminée' : 'fireplace',
        'amenity_interphone': 'interphone',
        'amenity_terrasses': 'terrace',
        'amenity_chauffage_électriques' : 'electric_heating',
        'amenity_ascenseur': 'elevator',
        'amenity_système_alarme': 'alarm_system',
        'amenity_accès_internet': 'internet_access',
        'amenity_vue_mer': 'sea_view',
        'amenity_meublé': 'furnished',
        'amenity_chauffage_centrale': 'central_heating',
        'amenity_cuisine_équipé': 'kitchen_equipped',


}

df = df.rename(columns=new_names)
df.columns.tolist()

['price',
 'property_type',
 'bedrooms',
 'bathrooms',
 'total_rooms',
 'living_area',
 'land_area',
 'construction_year',
 'neighborhood',
 'city',
 'climatisation',
 'parabole_tv',
 'pool',
 'handicapped_access',
 'parking',
 'garage',
 'garden',
 'fireplace',
 'interphone',
 'terrace',
 'electric_heating',
 'elevator',
 'alarm_system',
 'internet_access',
 'sea_view',
 'furnished',
 'central_heating',
 'kitchen_equipped']

In [184]:
# Drop rows where price is null
df = df.dropna(subset=['price'])

# Verify the change
print(f"Number of rows after removing null prices: {len(df)}")

Number of rows after removing null prices: 14352


In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14352 entries, 0 to 16062
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   price               14352 non-null  float64
 1   property_type       14352 non-null  object 
 2   bedrooms            11072 non-null  float64
 3   bathrooms           10163 non-null  float64
 4   total_rooms         8585 non-null   float64
 5   living_area         14352 non-null  float64
 6   land_area           14352 non-null  float64
 7   construction_year   3765 non-null   float64
 8   neighborhood        14344 non-null  object 
 9   city                14344 non-null  object 
 10  climatisation       14352 non-null  int64  
 11  parabole_tv         14352 non-null  int64  
 12  pool                14352 non-null  int64  
 13  handicapped_access  14352 non-null  int64  
 14  parking             14352 non-null  int64  
 15  garage              14352 non-null  int64  
 16  garden   

In [186]:
df['bedrooms'].unique()

array([3.00000e+00, 1.00000e+00, 2.00000e+00, 4.00000e+00,         nan,
       7.00000e+00, 5.00000e+00, 6.00000e+00, 1.38184e+05, 1.33185e+05,
       9.00000e+00, 8.00000e+00, 4.51560e+04, 4.43550e+04, 2.90000e+05,
       1.33057e+05, 1.16349e+05, 7.14680e+04, 6.44080e+04, 6.29110e+04,
       4.17020e+04, 8.10700e+03, 3.57800e+03, 8.11000e+02])

In [187]:
df[df['bedrooms']=='290000']

Empty DataFrame
Columns: [price, property_type, bedrooms, bathrooms, total_rooms, living_area, land_area, construction_year, neighborhood, city, climatisation, parabole_tv, pool, handicapped_access, parking, garage, garden, fireplace, interphone, terrace, electric_heating, elevator, alarm_system, internet_access, sea_view, furnished, central_heating, kitchen_equipped]
Index: []

[0 rows x 28 columns]

this miss writing from the user 

In [188]:
df = df[df['bedrooms'] != '290000']

In [189]:
df['bedrooms'].unique()

array([3.00000e+00, 1.00000e+00, 2.00000e+00, 4.00000e+00,         nan,
       7.00000e+00, 5.00000e+00, 6.00000e+00, 1.38184e+05, 1.33185e+05,
       9.00000e+00, 8.00000e+00, 4.51560e+04, 4.43550e+04, 2.90000e+05,
       1.33057e+05, 1.16349e+05, 7.14680e+04, 6.44080e+04, 6.29110e+04,
       4.17020e+04, 8.10700e+03, 3.57800e+03, 8.11000e+02])

In [190]:
df[df['bedrooms']=='138184']

Empty DataFrame
Columns: [price, property_type, bedrooms, bathrooms, total_rooms, living_area, land_area, construction_year, neighborhood, city, climatisation, parabole_tv, pool, handicapped_access, parking, garage, garden, fireplace, interphone, terrace, electric_heating, elevator, alarm_system, internet_access, sea_view, furnished, central_heating, kitchen_equipped]
Index: []

[0 rows x 28 columns]

In [191]:
df.loc[df['bedrooms'] == '138184', 'bedrooms'] = '4'

C:\Users\MSI\AppData\Local\Temp\ipykernel_25068\171684643.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['bedrooms'] == '138184', 'bedrooms'] = '4'


In [192]:
df['bedrooms'].unique()

array([3.0, 1.0, 2.0, 4.0, nan, 7.0, 5.0, 6.0, 138184.0, 133185.0, 9.0,
       8.0, 45156.0, 44355.0, 290000.0, 133057.0, 116349.0, 71468.0,
       64408.0, 62911.0, 41702.0, 8107.0, 3578.0, 811.0], dtype=object)

In [193]:
df[df['bedrooms']=='45156']

Empty DataFrame
Columns: [price, property_type, bedrooms, bathrooms, total_rooms, living_area, land_area, construction_year, neighborhood, city, climatisation, parabole_tv, pool, handicapped_access, parking, garage, garden, fireplace, interphone, terrace, electric_heating, elevator, alarm_system, internet_access, sea_view, furnished, central_heating, kitchen_equipped]
Index: []

[0 rows x 28 columns]

this user wirte wrong his info 

In [194]:
# Update multiple values for rows where bedrooms is '45156'
df.loc[df['bedrooms'] == '45156', ['bedrooms', 'bathrooms', 'price']] = ['4', '2', 675000000]

C:\Users\MSI\AppData\Local\Temp\ipykernel_25068\1775607679.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['bedrooms'] == '45156', ['bedrooms', 'bathrooms', 'price']] = ['4', '2', 675000000]


In [195]:
df['bedrooms'].unique()

array([3.0, 1.0, 2.0, 4.0, nan, 7.0, 5.0, 6.0, 138184.0, 133185.0, 9.0,
       8.0, 45156.0, 44355.0, 290000.0, 133057.0, 116349.0, 71468.0,
       64408.0, 62911.0, 41702.0, 8107.0, 3578.0, 811.0], dtype=object)

In [196]:
df.loc[df['bedrooms'] == '133185', 'bedrooms'] = '3'


In [197]:
df = df[df['bedrooms'] != '44355']

In [198]:
df.loc[df['bedrooms'] == '133057', 'bedrooms'] = '2'

In [199]:
df.loc[df['bedrooms'] == '116349', 'bedrooms'] = '9'

In [200]:
df.loc[df['bedrooms'] == '71468', 'bedrooms'] = '4'

In [201]:
df.loc[df['bedrooms'] == '64408', 'bedrooms'] = '3'

In [202]:
df.loc[df['bedrooms'] == '62911', 'bedrooms'] = '3'

In [203]:
df.loc[df['bedrooms'] == '41702', 'bedrooms'] = '4'

In [204]:
df = df[df['bedrooms'] != '8107']


In [205]:
df.loc[df['bedrooms'] == '3578', 'bedrooms'] = '2'

In [206]:
df.loc[df['bedrooms'] == '811', 'bedrooms'] = '2'

In [207]:
df['price'].unique()

array([1.25e+06, 3.60e+05, 3.20e+05, ..., 2.70e+04, 1.25e+07, 7.50e+07],
      shape=(1298,))

Top 10 minimum prices:
12      1.0
282     1.0
295     1.0
531     1.0
544     1.0
559     1.0
574     1.0
577     1.0
691     1.0
1010    1.0
Name: price, dtype: float64


In [209]:
df = df[df['price'] != 1]


In [210]:
df.shape

(14260, 28)

In [211]:
df = df.dropna(subset=['bedrooms'])

In [212]:
df.shape

(11002, 28)

In [217]:
df['bedrooms'].unique()

array([3.0, 1.0, 2.0, 4.0, 7.0, 5.0, 6.0, 138184.0, 133185.0, 9.0, 8.0,
       44355.0, 290000.0, 133057.0, 64408.0, 3578.0, 811.0], dtype=object)

In [218]:
df[df['bedrooms']!= '133185.0']

price property_type bedrooms bathrooms  total_rooms  living_area  \
0      1250000.0   Appartement      3.0       NaN          4.0        178.0   
1       360000.0   Appartement      3.0       NaN          4.0        110.0   
2       320000.0   Appartement      1.0       1.0          NaN         53.0   
3       422000.0   Appartement      2.0       2.0          3.0        125.0   
4       245000.0   Appartement      1.0       1.0          2.0         74.0   
...          ...           ...      ...       ...          ...          ...   
16057   220000.0        Maison      3.0       2.0          4.0        170.0   
16059   175000.0        Maison      3.0       2.0          6.0        157.0   
16060   255000.0        Maison      4.0       NaN          6.0        455.0   
16061   450000.0        Maison      5.0       3.0          8.0        650.0   
16062   300000.0        Maison      6.0       2.0          8.0        200.0   

       land_area  construction_year    neighborhood       city  ...  \
0          178.0                NaN        La Marsa      Tunis  ...   
1          110.0                NaN        La Marsa      Tunis  ...   
2            0.0                NaN        La Marsa      Tunis  ...   
3          125.0             2022.0       La Soukra     Ariana  ...   
4            0.0             2024.0          Mrezga     Nabeul  ...   
...          ...                ...             ...        ...  ...   
16057      476.0             2013.0        Monastir   Monastir  ...   
16059      157.0             2017.0         Sbeïtla  Kasserine  ...   
16060      435.0             2007.0  Kasserine Nord  Kasserine  ...   
16061     1170.0             2015.0  Kasserine Nord  Kasserine  ...   
16062      600.0             2006.0        Djedeida    Manouba  ...   

       interphone  terrace  electric_heating  elevator  alarm_system  \
0               1        1                 1         1             1   
1               1        1                 1         1             1   
2               1        1                 1         1             1   
3               0        0                 0         0             1   
4               0        0                 1         1             0   
...           ...      ...               ...       ...           ...   
16057           0        0                 1         1             1   
16059           1        1                 1         1             1   
16060           1        0                 1         1             1   
16061           0        0                 1         1             1   
16062           1        1                 1         1             1   

       internet_access  sea_view  furnished  central_heating  kitchen_equipped  
0                    1         1          0                1                 1  
1                    1         1          1                1                 1  
2                    1         1          1                1                 1  
3                    0         1          1                0                 0  
4                    0         1          1                0                 0  
...                ...       ...        ...              ...               ...  
16057                0         1          1                0                 0  
16059                1         1          1                1                 1  
16060                1         1          1                1                 0  
16061                1         1          0                0                 0  
16062                1         1          1                1                 1  

[9029 rows x 28 columns]

In [ ]:
df.loc[df['bedrooms'] == '3578', 'bedrooms'] = '2'

In [214]:
min_prices = df['price'].nsmallest(20)
print("Top 10 minimum prices:")
print(min_prices)

Top 10 minimum prices:
333       2.0
2306      2.0
7713      2.0
8275      2.0
10760     2.0
10695     5.0
8697      6.0
11337     8.0
11187     9.0
11338     9.0
11411     9.0
9338     10.0
11103    10.0
10455    11.0
11173    15.0
15669    17.0
307      22.0
4877     28.0
8791     28.0
500      30.0
Name: price, dtype: float64


In [215]:
df = df[df['price'] >= 80000]


In [216]:
# # Save the cleaned DataFrame to CSV with proper encoding
# output_path = r'c:\Users\MSI\Desktop\House Sale Price Prediction\CSV\menzili_properties.csv'

# # Create directory if it doesn't exist
# import os
# os.makedirs(os.path.dirname(output_path), exist_ok=True)

# # Save to CSV with UTF-8 encoding
# df.to_csv(output_path, index=False, encoding='utf-8-sig')

# # Verify the save
# if os.path.exists(output_path):
#     print(f"Data saved successfully to: {output_path}")
#     print(f"File size: {os.path.getsize(output_path) / (1024*1024):.2f} MB")
# else:
#     print("Error: File was not saved properly")